@startuml Executor类图
title Executor类图

interface CommandExecutor<E extends CommandExecutor<E>> {
  + getExecutableCmdBuilder(): ExecutableCmdBuilder
  + forceNative(): E
  + namedParameter(): E
}

interface QueryCommandExecutor<E extends QueryCommandExecutor<E>> extends CommandExecutor {
  + paginate(int pageNum, int pageSize): E
  + limit(int offset, int size): E
  + disableCount(): E
  + findCount(): long
  + findOne(Class<T> cls): T
  + findOneForMap(): Map<String, Object>
  + findOneForScalar(Class<T> clazz): T
  + findList(Class<T> cls): List<T>
  + findListForMap(): List<Map<String, Object>>
  + findListForScalar(Class<T> clazz): List<T>
  + findFirst(Class<T> cls): T
  + findFirstForMap(): Map<String, Object>
  + findFirstForScalar(Class<T> clazz): T
  + findPage(Class<T> cls): Page<T>
  + findPageForMap(): Page<Map<String, Object>>
  + findPageForScalar(Class<T> clazz): Page<T>
  + default paginate(Pageable pageable): E
}

interface ConditionCommandExecutor<E extends ConditionCommandExecutor<E>> extends CommandExecutor {
  + where(): E
  + where(String field, Object value): E
  + where(String field, SqlOperator sqlOperator, Object value): E
  + where(GetterFunction<T> getter, Object value): E
  + where(GetterFunction<T> getter, SqlOperator sqlOperator, Object value): E
  + condition(String field, Object value): E
  + condition(String field, SqlOperator sqlOperator, Object value): E
  + condition(GetterFunction<T> getter, Object value): E
  + condition(GetterFunction<T> getter, SqlOperator sqlOperator, Object value): E
  + whereForBean(Object bean): E
  + whereForBeanPrimaryKey(Object bean): E
  + appendSegment(String segment): E
  + appendSegment(String segment, Object value): E
  + openParen(): E
  + closeParen(): E
  + and(): E
  + and(String field, Object value): E
  + and(String field, SqlOperator sqlOperator, Object value): E
  + and(GetterFunction<T> getter, Object value): E
  + and(GetterFunction<T> getter, SqlOperator sqlOperator, Object value): E
  + or(): E
  + or(String field, Object value): E
  + or(String field, SqlOperator sqlOperator, Object value): E
  + or(GetterFunction<T> getter, Object value): E
  + or(GetterFunction<T> getter, SqlOperator sqlOperator, Object value): E
}

interface Select<M> extends QueryCommandExecutor, ConditionCommandExecutor {
  + as(String alias): Select
  + addColumns(Class<?> clazz): Select
  + addColumn(String... fields): Select
  + addAliasColumn(String tableAlias, String... fields): Select
  + addColumn(GetterFunction<T> getter): Select
  + dropColumn(String... fields): Select
  + dropColumn(GetterFunction<T> getter): Select
  + join(String table): Select
  + join(Class<?> cls): Select
  + innerJoin(String table): Select
  + innerJoin(Class<?> cls): Select
  + outerJoin(String table): Select
  + outerJoin(Class<?> cls): Select
  + leftJoin(String table): Select
  + leftJoin(Class<?> cls): Select
  + rightJoin(String table): Select
  + rightJoin(Class<?> cls): Select
  + on(String on): Select
  + on(GetterFunction<T1> table1Field, GetterFunction<T2> table2Field): Select
  + on(GetterFunction<T1> table1Field, SqlOperator sqlOperator, GetterFunction<T2> table2Field): Select
  + groupBy(String... fields): Select
  + groupBy(GetterFunction<T> getter): Select
  + orderBy(String field, OrderBy orderBy): Select
  + orderBy(GetterFunction<T> getter, OrderBy orderBy): Select
  + having(String having, SqlOperator sqlOperator, Object value): Select
  + having(GetterFunction<T> getter, SqlOperator sqlOperator, Object value): Select
  + findOne(): M
  + findFirst(): M
  + findList(): List<M>
  + findPage(): Page<M>
}

interface Update extends ConditionCommandExecutor {
  + table(Class<?> cls): Update
  + set(String field, Object value): Update
  + set(GetterFunction<T> getter, Object value): Update
  + setForBean(Object bean): Update
  + updateNull(): Update
  + execute(): int
}

interface Delete extends ConditionCommandExecutor {
  + from(Class<?> cls): Delete
  + execute(): int
}

interface Insert extends CommandExecutor {
  + into(Class<?> cls): Insert
  + intoField(String field, Object value): Insert
  + intoField(GetterFunction<T> getter, Object value): Insert
  + intoForObject(Object obj): Insert
  + execute(): Object
}

interface SimpleCommandExecutor<E extends SimpleCommandExecutor<E>> extends QueryCommandExecutor {
  + command(String command): E
  + parameters(Map<String, Object> parameters): E
  + parameter(String name, Object value): E
  + parameter(BeanParameter beanParameter): E
  + resultHandler(ResultHandler<M> resultHandler): E
  + insert(): Serializable
  + insert(Class<?> clazz): Serializable
  + update(): int
  + execute(): void
  + executeScript(): void
}

interface NativeExecutor extends SimpleCommandExecutor {
  + parameters(Object... parameters): NativeExecutor
}

interface MybatisExecutor extends SimpleCommandExecutor {

}

interface BatchUpdateExecutor extends CommandExecutor {
  + execute(String command, Collection<T> batchData, int batchSize, ParameterizedSetter<T> parameterizedSetter): Object
}

@enduml
